apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cloud-todo-cluster
  region: ap-south-1
nodeGroups:
  - name: ng-standard
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
